export { default as About } from './About';
export { default as Contacts, Contact } from './Contacts';
export { default as Fonts } from './Fonts';
export { default as Footer } from './Footer';
export { Hero } from './Hero';
export { default as MotionLink } from './MotionLink';
export { Navbar } from './Navbar';
export { default as Projects, Project } from './Projects';
export { default as ScrollUp } from './ScrollUp';
export { default as Section } from './Section';
export { default as Skills, Skill } from './Skills';
export { default as ThemeScript, themeToggleId } from './ThemeScript';
